trigger:
    batch: true
    branches:
        include:
        - main
        - develop
    paths:
        include: 
        - "./SchoolApi/*"

pool:
  name: 'Azure Pipelines'


variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')] #not used
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')] #not used
  test: ""

stages:
- template: templates/stage_level_templates/test_build_stage_template.yml # stage template to test, build and push
  parameters:
    projectFolder: Satya/SchoolApi/SchoolApi.sln #${{variables.projectFolder}}
    buildOutputFolder: $(BUILDOUTPUTFOLDER) #${{variables.buildOutputFolder}}
    sourceFolder: $(SOURCEFOLDER) #${{variables.sourceFolder}}
    vmImageName: $(VMIMAGE)
    

- template: templates/stage_level_templates/az_deployment_stage_template.yml # stage template for azure resource deployment to Develop
  parameters:
    vmImageName : $(VMIMAGE) #${{variables.vmImage}}
    azureSubscription : "SchoolApi"
    resourceGroup : "SatyaResource"
    bicepFilePath : "Satya/SchoolApi/infrastructure/main.bicep"
    parameterFilePath : "Satya/SchoolApi/infrastructure/main.parameters.dev.json"
    jobName : "resourcedeployment"
    jobDescription : "deployemnt of resources"
    scriptType : "bash"
    environment: 'dev'
    deploy: true

- template: templates/stage_level_templates/app_deployment_stage_template.yml #stage template for application deployment
  parameters:
    serviceConnection: "SchoolApi"
    subscriptionId: 'dev'
    environment: 'dev'
    appType: $(APPTYPE)
